# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bingyan.me
email: bingyan@mit.edu
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bingyan.me/" # the base hostname & protocol for your site
twitter_username: bing__yan
github_username: BYan6667

# Build settings
markdown: kramdown
highlighter: rouge
